artifact_location: file:///c:/Users/Pichau/Documents/GitHub Portfolio/dl-knn-svm/notebooks/runs/mlflow/677678534301794409
creation_time: 1753998910864
experiment_id: '677678534301794409'
last_update_time: 1753998910864
lifecycle_stage: active
name: /Shared/Ultralytics
